beacon-biosignals/Onda.jl

src/recordings.jl
This statement should always execute even if assertions are disabled
=> switch assert to conditional

codecov.yml, examples/flac.jl, src/samples.jl, src/serialization.jl
This PR is a stepping stone towards resolving #5; it doesn't quite go all the way though, since `load_samples`/`store_samples!` aren't exported/documented API functions.
I mainly whipped up this PR to test if we get Codecov status reports 😛
=> allow kwargs to serializer(...) + allow caller to pass serializer to load_samples/store_samples!

src/dataset.jl, src/samples.jl, src/timespans.jl, test/dataset.jl, test/timespans.jl
Ref https://github.com/jrevels/YASGuide/pull/17. I just ran into this: got an assertion about `first <= last` with no indication of what the values actually were.
=> Use explicit errors rather than assertions

src/dataset.jl, test/dataset.jl
It's handy to be able to create a recording based on a pre-computed UUID, like when converting data from another format which uses UUIDs to Onda. This change adds a `uuid` argument to `create_recording!` that defaults to `uuid4()`, and adds a check to ensure that the provided UUID does not already exist in the dataset. Tests are added/adjusted accordingly.
=> Allow passing a UUID to `create_recording!`

src/recordings.jl, src/timespans.jl, test/dataset.jl
For `TimeSpan` we check that the start precedes the end, but we don't do that for `Annotation`. Ideally this should be a required check for all `AbstractTimeSpan`s, but alas, there's not really a way to enforce that.
This would have saved me so much time. ;-;
=> Ensure invalid `Annotation`s can't be constructed

docs/src/index.md, examples/flac.jl, src/serialization.jl, test/serialization.jl
note this is a technically a breaking change, but hopefully not much downstream code is defining new `AbstractLPCMSerializer` subtypes yet (if they were, it was probably already broken lol)
fixes #21, hopefully (@hannahilea can you test this out to ensure it works for your use case - it's kinda hard to test precompilation stuff as part of CI...we could but it's not worth the effort right now)
=> replace extension mapping mechanism for AbstractLPCMSerializer with one that works with precompilation

docs/src/index.md
this was supposed to be here, was an oversight that it wasn't
=> add time_from_index/index_from_time to docs

Project.toml
CodecZstd 0.7.0 requires Julia 1.3 and accesses zstd via a JLL. See https://github.com/JuliaIO/CodecZstd.jl/pull/20 for more information.
In the interest of releasing a version of Onda that supports the new version of CodecZstd, this also bumps the patch version.
=> Allow CodecZstd 0.7, bump version to 0.8.1

src/Onda.jl
@ararslan and I just spent about 7 hours reducing some upstream OOMs down to calls to this little devil. Specifically, our entrypoint to this was via `Onda.load(..., ::TimeSpan)` on some zstd-compressed signals. We don't have a good full MWE, but just calling it over and over ~100 times (for us, on ~1GB (decompressed) of data each call) should trigger it. 
When we first realized it was this, I was going to just delete this method, but I guess adding a warning is probably better for now (it's at least less breaking). Note that we're not sure what exactly causes the issue (maybe TranscodingStreams/CodecZstd streaming issue, or our usage of that package...?). Will file a corresponding issue to actually resolve this at some point, but that will require a good amount of debugging and isn't …
=> add warning to memory-leaky zstd-based deserialization method

docs/src/index.md, src/Onda.jl, src/dataset.jl, src/recordings.jl, src/samples.jl, src/timespans.jl, test/dataset.jl
resolves #30, #33 
-  the previous on-`store!`-only Signal validation also occurs upon construction 
- the previous on-construction-only Samples validation also occurs upon `store!`
- allows users to toggle `validate_on_construction` so that you can still have a chance at reading malformed datasets (but `validate_on_construction` is `true` by default)
- validates that Samples/Signal durations match upon `store!`
still needs tests/docs
=> validation improvements 

src/timespans.jl
This function is "new" in Julia 1.5 (https://github.com/JuliaLang/julia/pull/35132). This change will avoid breaking the package on Julia nightly.
=> Extend `contains` from Base when defined

src/timespans.jl, test/timespans.jl
Since we have type piracy on types from Dates to allow them to act like `TimeSpan`s, they could be used in `contains` until the signature was restricted to `AbstractTimeSpan`s in #41 to mitigate breakage from `contains` being reintroduced to Base.
I tried briefly to remove the type piracy, but there's a lot of `first`/`last` usage that would be annoying to work around.
=> Add method inadvertently removed in #41

Project.toml, src/timespans.jl, test/timespans.jl
A one-liner to allow MsgPack (de)serialization of `TimeSpan`'s.
=> Add `msgpack_type(::Type{TimeSpan})`

Project.toml, src/dataset.jl
I think these were missed in #47.
=> Avoid dep warnings from non-deprecated function calls

Project.toml, docs/src/index.md, src/Onda.jl, src/dataset.jl, src/samples.jl, test/dataset.jl
I actually don't have feelings on this either way, but opening as an RFC after @palday mentioned for many users:
> the idea of having to load and decode just adds mental overhead that they don't care about because of course you want to decode as soon as load. 
Can update tests/docs/examples/etc. if folks prefer this.
=> rename load to load_encoded, define load to decode Samples by default

Project.toml, examples/tour.jl, src/samples.jl, test/samples.jl
This doesn't support nesting, e.g. `samples[[r"o", "f1"], :]`, but we also don't support mixing unit ranges with strings, for example, because one returns a vector of channels and the other a scalar, so I think it's coherent.
=> Allow indexing channel names by regex

.github/workflows/CI.yml
not something we claim to support and upstream failures are causing CI to look like it's failing here
=> do not test on Julia nightly

.github/workflows/TagBot.yml, Project.toml
Looks like Onda's stable docs have been silently (?) failing to update for a while - note the docstring here on the most recent tag:
https://github.com/beacon-biosignals/Onda.jl/blob/v0.13.6/src/annotations.jl#L68-L76
The actual rendered docstring on `stable` still has the materialize kwarg that was deprecated a while ago:
https://beacon-biosignals.github.io/Onda.jl/stable/#Onda.read_annotations
I'm suspecting it's this https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions
> In order to deploy documentation for tagged versions, the GitHub Actions workflow needs to be triggered by the tag. However, by default, when the Julia TagBot uses just the GITHUB_TOKEN for authentication, it does not have the permission to trigger any further workflows jobs, and so the …
=> add DOCUMENTER_KEY to TagBot.yml to attempt to fix docs for tagged releases

.github/workflows/CI.yml, Project.toml, examples/flac.jl
Testing locally was failing due to not having `flac` on my system. Better to use FLAC_jll for this to avoid the implicit system dependency.
=> Use FLAC_jll to avoid implicit system dependency

Project.toml, src/Onda.jl, src/utilities.jl
Avoids having duplicate code and allows Onda to use this fix once merged: https://github.com/beacon-biosignals/Legolas.jl/pull/26
=> Use `write_full_path` from Legolas

Project.toml, src/annotations.jl, test/annotations.jl
This is pretty useful! TimeSpans has `merge_spans` which does this (with the same semantics), but it is helpful to have the feature at the level of annotations.
=> allow customizing predicate in `merge_overlapping_annotations`

Project.toml, src/samples.jl, src/signals.jl, test/samples.jl
I have seen a proliferation of `deepcopy` on Samples objects in Beacon-internal projects, and generally when I see `deepcopy` I think there's a missing `copy` method.  
The internal use cases I have seen generally have the requirement that the data is copied, as well as the `channels` vector in the info object. E.g. you may want to `copy`, then perform an in-place montaging that updates the `channels` vector, and want the original unaffected.
That motivated the implementation here, where we shallow-copy each field of the `SamplesInfo`.
If we don't like this approach we could decide `deepcopy` is indeed the right approach for this. I benchmarked after implementing, and here `deepcopy` isn't that bad for performance (probably because it's mostly a big chunk of contiguous data, which Julia's …
=> add `Base.copy` implementation

docs/Project.toml
For some reason, the ["dev"](https://beacon-biosignals.github.io/Onda.jl/dev/) docs are out of date. Maybe a newer documenter version will fix this?
=> Bump documenter version

Project.toml, src/samples.jl, test/samples.jl
Currently, the error that's thrown when a channel is not found is pretty hard to
interpret (complains about indexing with a `nothing`).  This PR adds a check
which intercepts the `nothing` returned by `channel(...)` when a channel is not
found, and throws a better error which mentions the channel not found by name.
This doesn't cover _all_ the scenarios (e.g., if there are >1 channels not
found, it'll only raise the first one) but it's an improvement that's not
breaking (and so can be backported to a 0.14 release).
=> throw an informative error when a channel is not found

Project.toml, ext/OndaAWSS3Ext.jl, test/awss3.jl, test/runtests.jl
To automatically use the efficient byte-range method when AWSS3 is loaded, on Julia 1.9+. This is currently pirated in various places, which should be removed on 1.9+.
I have used the strategy from [here](https://pkgdocs.julialang.org/v1/creating-packages/#Using-an-extension-while-supporting-older-Julia-versions) such that the feature is only present on 1.9+, but there's no dependency cost pre-1.9. An alternative would be to add AWSS3 as a full dependency pre-1.9.
=> add AWSS3 as a package extension

Project.toml, src/samples.jl, test/samples.jl
The test I added fails on main:
```julia
julia> @test hash(samples) == hash(samples2)
Test Failed at REPL[23]:1
Expression: hash(samples) == hash(samples2)
Evaluated: 0x9bab1974999310ac == 0x877a3e1403901e84
```
but passes on this PR.
closes https://github.com/beacon-biosignals/Onda.jl/issues/150
=> fix bug in hashing samples

Project.toml, src/samples.jl
closes https://github.com/beacon-biosignals/Onda.jl/issues/146
Here the main question is whether to use `muladd` or `fma`. Quoting the `muladd` doctsring,
> help?> Base.muladd
>   muladd(x, y, z)
> 
>   Combined multiply-add: computes x*y+z, but allowing the add and multiply to be merged with each other or with surrounding operations for
>   performance. For example, this may be implemented as an fma if the hardware supports it efficiently. The result can be different on different
>   machines and can also be different on the same machine due to constant propagation or other optimizations. See fma.
The result being different on different machines sounds like the kind of thing we don't want to have to worry about with encode/decode when trying to track down reproducibility issues etc. …
=> use fma in decoding

Project.toml, src/samples.jl, test/samples.jl
closes #156 
I chose not to update the encoding parameters when converting encoded samples, since that seemed like a change we don't want to make implicitly.
=> define `convert` for Samples

Project.toml, src/serialization.jl
This PR also removes the use of the internal `TranscodingStreams.changemode!` function. This function may be broken in a future release of `TranscodingStreams`. Ref: https://github.com/JuliaVTK/WriteVTK.jl/pull/137
TranscodingStreams v0.11 release notes: https://github.com/JuliaIO/TranscodingStreams.jl/releases/tag/v0.11.0
This release shouldn't effect this package because from what I can tell there is no use of `eof`, `seekend`, or `TranscodingStreams.Memory`
=> Bump TranscodingStreams compat

Project.toml, src/samples.jl, test/samples.jl
At present, we error on `convert(::Type{Samples{A}}, ::Samples{B})` for all `A` and `B` if the samples are encoded. This is reasonable since we don't want to affect how the samples get decoded. However, decoding should be based on the type of the encoded samples themselves rather than of their container; a decoder shouldn't care whether the incoming data is e.g. a full matrix or a view of a matrix. Thus we can allow conversion for encoded samples provided that only the container type is affected, not the element type.
cc @rebareh, who ran into this in some private Beacon code.
=> Allow `convert`ing encoded samples if the element type matches

Project.toml, docs/Project.toml, docs/src/index.md
The upgrade also causes what were previously warnings when building docs to now produce errors, which should prevent future docstrings from being missed and references from being broken.
=> Upgrade Documenter to 1.8 and add missing docstrings
